[package]
name = "qlight-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "qlight"
path = "src/main.rs"

[dependencies]
qlight-core = { path = "../qlight-core" }
hidapi = "2.6.4"
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
