[package]
name = "qlight-osc"
version.workspace = true
edition.workspace = true

[dependencies]
rosc = "~0.10"
qlight-core = { path = "../qlight-core" }
anyhow = "1.0.100"
hidapi = "2.6.4"
matchit = "0.9.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
